export const errors = {
	auth: {
		'account-inactivated': 'accountInactive',
		'email-existed': 'emailExisted',
		'key-duplicated': 'emailExisted',
		'invalid-authentication': 'invalidAuthentication',
		'missing-req-body': 'actionFailed',
		'validation-failed': 'actionFailed',
		'invalid-googleid': 'invalidGoogleId',
		'action-failed': 'actionFailed',
	},
	answer: {
		'invalid-question-id': 'actionFailed',
		'invalid-answer-id': 'actionFailed',
		'invalid-credentials': 'notPriviledged',
		failed: 'actionFailed',
		'missing-req-body': 'actionFailed',
		'already-gone': 'answerDeleted',
		'action-failed': 'actionFailed',
		'validation-failed': 'validationFailed',
	},
	cart: {
		'missing-req-body': 'actionFailed',
		'invalid-product-id': 'invalidProduct',
		'key-duplicated': 'alreadyInCart',
		failed: 'actionFailed',
		'action-failed': 'actionFailed',
	},
	category: {},
	comment: {
		'invalid-question-id': 'actionFailed',
		'invalid-answer-id': 'actionFailed',
		'invalid-root-id': 'actionFailed',
		'invalid-comment-id': 'actionFailed',
		'invalid-credentials': 'notPriviledged',
		failed: 'actionFailed',
		'already-gone': 'commentDeleted',
		'missing-req-body': 'actionFailed',
		'action-failed': 'actionFailed',
	},
	invoice: {
		'action-failed': 'actionFailed',
	},
	payment: {
		'invalid-shop-id': 'noShop',
		'invalid-paypal': 'missingPayPalEmail',
		failed: 'actionFailed',
		'action-failed': 'actionFailed',
	},
	product: {
		'invalid-category-id': 'actionFailed',
		'invalid-shop-id': 'actionFailed',
		'invalid-product-id': 'actionFailed',
		'action-failed': 'actionFailed',
	},
	profile: {
		'invalid-user-id': 'actionFailed',
		'action-failed': 'actionFailed',
	},
	question: {
		'invalid-question-id': 'questionNotFound',
		'missing-req-body': 'actionFailed',
		'invalid-answer-id': 'actionFailed',
		'invalid-credentials': 'notPriviledged',
		failed: 'actionFailed',
		'already-gone': 'actionFailed',
		'invalid-tag-id': 'actionFailed',
		'action-failed': 'actionFailed',
	},
	review: {
		'invalid-invoice-id': 'actionFailed',
		'missing-req-body': 'actionFailed',
		'missing-body': 'actionFailed',
		'action-failed': 'actionFailed',
	},
	shop: {
		'invalid-authentication': 'notPriviledged',
		'invalid-shop-id': 'shopNotFound',
		'invalid-product-id': 'productNotFound',
		'invalid-credentials': 'notPriviledged',
		failed: 'actionFailed',
		'already-gone': 'shopGone',
		'action-failed': 'actionFailed',
	},
	upload: {
		'missing-req-body': 'actionFailed',
		'action-failed': 'actionFailed',
	},
	user: {
		'invalid-user-id': 'userNotFound',
		'action-failed': 'actionFailed',
	},
	//Vote.id
	voting: {
		'invalid-answer-id': 'answerNotFound',
		'invalid-comment-id': 'commentNotFound',
		'invalid-question-id': 'questionNotFound',
		'invalid-amount': 'actionFailed',
		'missing-req-body': 'actionFailed',
		failed: 'actionFailed',
		'already-gone': 'actionFailed',
		'action-failed': 'actionFailed',
	},
};
