export enum actionTypes {
	AUTH_ERROR = 'AUTH_ERROR',
	AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST',
	AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS',
	AUTH_SIGNUP_REQUEST = 'AUTH_SIGNUP_REQUEST',
	AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS',
	AUTH_USER_SIGN_OUT = 'AUTH_USER_SIGN_OUT',
}
