const AUTH_SET_ACTIVE_USER = 'AUTH_SET_ACTIVE_USER';
const AUTH_USER_SIGN_OUT = 'AUTH_USER_SIGN_OUT';
const AUTH_ERROR = 'AUTH_ERROR';

export default { 
  AUTH_SET_ACTIVE_USER, 
  AUTH_ERROR,
  AUTH_USER_SIGN_OUT,
};